/*
 * In this model, the learner is provided with two sources of information about the language:
 *     1. the learner can ask membership queries
 *     2. the learner can ask equivalence queries
 */
#pragma once

#include "MinimallyAdequateTeacher.h"
#include "Language.h"
#include "ObservationTable.h"
#include "ContextFreeGrammar.h"

class Learner
{
public:
    Learner(MinimallyAdequateTeacher& mat);
    ~Learner();

    /*
     * Algorithm 5
     * Returns a correct CFG after p(n, l) steps, where
     *     p - polynomial such that the language L is in the set of all languages
     *         definable by a congruential CFG,
     *         and L is generated by a sub-congruential grammar in CNF
     *     n - number of non-terminals
     *     l - maximum length of examples returned by the equivalence oracle
     */
    ContextFreeGrammar LearnCFG();

private:
    MinimallyAdequateTeacher& _mat;
};
